config/routes.rb
Rails.application.routes.draw do
  resources :emessages
  get 'pages/about'
  get 'pages/info'
  root "pages#homepage"
  resources :ecards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ecard.rb
class Ecard < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

app/models/emessage.rb
class Emessage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ecards_controller.rb
class EcardsController < ApplicationController
  before_action :set_ecard, only: %i[ show edit update destroy ]

  # GET /ecards or /ecards.json
  def index
    @ecards = Ecard.all
  end

  # GET /ecards/1 or /ecards/1.json
  def show
  end

  # GET /ecards/new
  def new
    @ecard = Ecard.new
  end

  # GET /ecards/1/edit
  def edit
  end

  # POST /ecards or /ecards.json
  def create
    @ecard = Ecard.new(ecard_params)

    respond_to do |format|
      if @ecard.save
        format.html { redirect_to ecard_url(@ecard), notice: "Ecard was successfully created." }
        format.json { render :show, status: :created, location: @ecard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ecards/1 or /ecards/1.json
  def update
    respond_to do |format|
      if @ecard.update(ecard_params)
        format.html { redirect_to ecard_url(@ecard), notice: "Ecard was successfully updated." }
        format.json { render :show, status: :ok, location: @ecard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ecards/1 or /ecards/1.json
  def destroy
    @ecard.destroy!

    respond_to do |format|
      format.html { redirect_to ecards_url, notice: "Ecard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ecard
      @ecard = Ecard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ecard_params
      params.require(:ecard).permit(:name, :description, :picture)
    end
end

app/controllers/emessages_controller.rb
class EmessagesController < ApplicationController
  before_action :set_emessage, only: %i[ show edit update destroy ]

  # GET /emessages or /emessages.json
  def index
    @emessages = Emessage.all
  end

  # GET /emessages/1 or /emessages/1.json
  def show
  end

  # GET /emessages/new
  def new
    @emessage = Emessage.new
  end

  # GET /emessages/1/edit
  def edit
  end

  # POST /emessages or /emessages.json
  def create
    @emessage = Emessage.new(emessage_params)

    respond_to do |format|
      if @emessage.save
        format.html { redirect_to emessage_url(@emessage), notice: "Emessage was successfully created." }
        format.json { render :show, status: :created, location: @emessage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emessage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emessages/1 or /emessages/1.json
  def update
    respond_to do |format|
      if @emessage.update(emessage_params)
        format.html { redirect_to emessage_url(@emessage), notice: "Emessage was successfully updated." }
        format.json { render :show, status: :ok, location: @emessage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emessage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emessages/1 or /emessages/1.json
  def destroy
    @emessage.destroy!

    respond_to do |format|
      format.html { redirect_to emessages_url, notice: "Emessage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emessage
      @emessage = Emessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emessage_params
      params.require(:emessage).permit(:from_email, :to_email, :message, :ecard_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ecards_helper.rb
module EcardsHelper
end

app/helpers/emessages_helper.rb
module EmessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ecards/_ecard.html.erb
<div id="<%= dom_id ecard %>">
  <p>
    <strong>Name:</strong>
    <%= ecard.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= ecard.description %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= image_tag(ecard.picture_url, width: 600) if ecard.picture? %>
  </p>

</div>

app/views/ecards/_form.html.erb
<%= form_with(model: ecard) do |form| %>
  <% if ecard.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ecard.errors.count, "error") %> prohibited this ecard from being saved:</h2>

      <ul>
        <% ecard.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ecards/edit.html.erb
<h1>Editing ecard</h1>

<%= render "form", ecard: @ecard %>

<br>

<div>
  <%= link_to "Show this ecard", @ecard %> |
  <%= link_to "Back to ecards", ecards_path %>
</div>

app/views/ecards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ecards</h1>

<div id="ecards">
  <% @ecards.each do |ecard| %>
    <%= render ecard %>
    <p>
      <%= link_to "Show this ecard", ecard %>
    </p>
  <% end %>
</div>

<%= link_to "New ecard", new_ecard_path %>

app/views/ecards/new.html.erb
<h1>New ecard</h1>

<%= render "form", ecard: @ecard %>

<br>

<div>
  <%= link_to "Back to ecards", ecards_path %>
</div>

app/views/ecards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ecard %>

<div>
  <%= link_to "Edit this ecard", edit_ecard_path(@ecard) %> |
  <%= link_to "Back to ecards", ecards_path %>

  <%= button_to "Destroy this ecard", @ecard, method: :delete %>
</div>

app/views/emessages/_emessage.html.erb
<div id="<%= dom_id emessage %>">
  <p>
    <strong>From email:</strong>
    <%= emessage.from_email %>
  </p>

  <p>
    <strong>To email:</strong>
    <%= emessage.to_email %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= emessage.message %>
  </p>

  <p>
    <strong>Ecard:</strong>
    <%= emessage.ecard_id %>
  </p>

</div>

app/views/emessages/_form.html.erb
<%= form_with(model: emessage) do |form| %>
  <% if emessage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(emessage.errors.count, "error") %> prohibited this emessage from being saved:</h2>

      <ul>
        <% emessage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :from_email, style: "display: block" %>
    <%= form.text_field :from_email %>
  </div>

  <div>
    <%= form.label :to_email, style: "display: block" %>
    <%= form.text_field :to_email %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.label :ecard_id, style: "display: block" %>
    <%= form.number_field :ecard_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/emessages/edit.html.erb
<h1>Editing emessage</h1>

<%= render "form", emessage: @emessage %>

<br>

<div>
  <%= link_to "Show this emessage", @emessage %> |
  <%= link_to "Back to emessages", emessages_path %>
</div>

app/views/emessages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Emessages</h1>

<div id="emessages">
  <% @emessages.each do |emessage| %>
    <%= render emessage %>
    <p>
      <%= link_to "Show this emessage", emessage %>
    </p>
  <% end %>
</div>

<%= link_to "New emessage", new_emessage_path %>

app/views/emessages/new.html.erb
<h1>New emessage</h1>

<%= render "form", emessage: @emessage %>

<br>

<div>
  <%= link_to "Back to emessages", emessages_path %>
</div>

app/views/emessages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @emessage %>

<div>
  <%= link_to "Edit this emessage", edit_emessage_path(@emessage) %> |
  <%= link_to "Back to emessages", emessages_path %>

  <%= button_to "Destroy this emessage", @emessage, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECardsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">The ecards app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'pages', action: 'homepage') %>" href="/">Home</a>
      </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'ecards') %>" href="/ecards">Ecards</a>
          
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'pages', action: 'about') %>" href="/pages/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'pages', action: 'info') %>" href="/pages/info">Info</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="mt-5 text-center">
  <div class="container">
    Rails Girls <%= Time.now.year %>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find Catherine Berridge in app/views/pages/about.html.erb</p>

app/views/pages/homepage.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">The ecard app</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Welcome to my ecard app!</p>
  </div>
</div>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find your ultimate purpose </p>